name: Build and Push Backend to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'netflix_backend/**'
      - '.github/workflows/backend.yml'

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: netflix-backend

jobs:
  build-and-push:
    name: Build, Tag, and Push Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Backend image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./netflix_backend
          file: ./netflix_backend/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest